import html
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import streamlit as st

from api.schemas import MAX_QUESTION_CHARS
from dashboard.backend import (
    EXAMPLE_QUESTIONS,
    ApiBackend,
    BackendError,
    EmbeddedBackend,
    build_embedded_service,
    load_seed_answers,
)
from dashboard.components import (
    STYLE,
    render_badge,
    render_chunk_card,
    render_meter,
    render_sources,
    render_strategy_chip,
)

GITHUB_URL = "https://github.com/NeelakshG/RAG_System"
# data/ isn't in git, so the hosted demo reads a committed copy instead
# (scripts/record_demo_answers.py copies it over).
COMPARISON_PATHS = [REPO_ROOT / "data" / "eval" / "comparison.json", REPO_ROOT / "dashboard" / "eval_comparison.json"]
COMPARISON_PATH = next((p for p in COMPARISON_PATHS if p.exists()), COMPARISON_PATHS[0])


def _export_secrets_to_env() -> None:
    """Streamlit Community Cloud stores settings in st.secrets. Copy the
    top-level string values into the environment so Config (which reads
    RAG_* env vars) picks them up. Real env vars win. No secrets file
    (the normal local setup) is fine."""
    try:
        secrets = dict(st.secrets)
    except Exception:
        return
    for key, value in secrets.items():
        if isinstance(value, (str, int, float, bool)) and key not in os.environ:
            os.environ[key] = str(value)


_export_secrets_to_env()
# "api" (default): talk to the FastAPI service. "embedded": run the pipeline
# in this process -- the public demo on Streamlit Community Cloud.
BACKEND_MODE = os.environ.get("RAG_DASHBOARD_BACKEND", "api")
IS_DEMO = BACKEND_MODE == "embedded"


@st.cache_resource(show_spinner="Loading models and indexing the demo documents (first visit only)...")
def get_backend(mode: str):
    """One backend per server process, shared by every visitor. `mode` is
    part of the cache key, so changing RAG_DASHBOARD_BACKEND in the app's
    secrets takes effect without a reboot."""
    if mode == "embedded":
        from config import Config

        service = build_embedded_service(REPO_ROOT)
        return EmbeddedBackend(
            service,
            max_new_questions_per_minute=Config().demo_new_questions_per_minute,
            seed_answers=load_seed_answers(),
        )
    return ApiBackend(
        os.environ.get("API_BASE_URL", "http://localhost:8000"),
        # Sent on write endpoints. Lives only on the dashboard's server side,
        # so visitors never see it.
        api_key=os.environ.get("RAG_API_KEY") or None,
    )


def questions_per_session() -> int:
    from config import Config

    return Config().demo_questions_per_session


st.set_page_config(page_title="RAG Pipeline", layout="wide")
st.markdown(STYLE, unsafe_allow_html=True)

st.title("RAG Pipeline")
if IS_DEMO:
    st.caption("Hybrid search, grounded generation, verified citations.")
    st.info(
        "**Live demo on free hosting.** Answers are generated by Llama 3.1 through Groq's free tier, "
        "over a small synthetic set of internal docs. The project itself runs fully local with Ollama. "
        f"[Source code and details on GitHub]({GITHUB_URL})."
    )
else:
    st.caption("Hybrid search, grounded generation, verified citations — all local.")

backend = get_backend(BACKEND_MODE)

tab_ask, tab_documents, tab_eval = st.tabs(["Ask", "Documents", "Eval comparison"])


def run_question(question: str, use_hybrid: bool, source_names: list[str] | None) -> None:
    """Ask and store the result, applying the per-visitor limit in the demo.
    Cached answers are free, so they don't count toward the limit."""
    cached = backend.is_cached(question, use_hybrid, source_names)
    if IS_DEMO and not cached:
        limit = questions_per_session()
        if st.session_state.get("questions_asked", 0) >= limit:
            st.warning(
                f"You've used this demo's {limit} new questions for this session, which keeps the free "
                "quota available for everyone. The example questions still work."
            )
            return
    with st.spinner("Retrieving, generating, and verifying citations..."):
        try:
            st.session_state["last_result"] = backend.ask(question, use_hybrid, source_names)
        except BackendError as e:
            st.error(str(e))
            return
    if IS_DEMO and not cached:
        st.session_state["questions_asked"] = st.session_state.get("questions_asked", 0) + 1


with tab_ask:
    scope = st.radio(
        "Search scope",
        ["All documents", "Specific documents"],
        horizontal=True,
        help="Restricting to specific documents skips embedding/reranking the rest of the "
        "corpus for this question -- faster, and avoids spending tokens on irrelevant context.",
    )

    selected_sources: list[str] = []
    if scope == "Specific documents":
        try:
            doc_names = [d["source_name"] for d in backend.documents()]
        except BackendError as e:
            doc_names = []
            st.error(f"Couldn't load document list: {e}")
        selected_sources = st.multiselect("Documents to search", doc_names)

    if IS_DEMO:
        st.markdown('<div class="section-label">Try an example</div>', unsafe_allow_html=True)
        example_columns = st.columns(len(EXAMPLE_QUESTIONS))
        for column, example in zip(example_columns, EXAMPLE_QUESTIONS):
            if column.button(example, key=f"example-{example}", width="stretch"):
                run_question(example, True, None)

    with st.form("ask_form"):
        question = st.text_input(
            "Question", placeholder="What does ERR_2043 indicate?", max_chars=MAX_QUESTION_CHARS
        )
        use_hybrid = st.toggle("Hybrid search (dense + sparse)", value=True)
        submitted = st.form_submit_button("Ask")

    if submitted and question.strip():
        if scope == "Specific documents" and not selected_sources:
            st.warning('Select at least one document, or switch to "All documents".')
        else:
            sources = selected_sources if scope == "Specific documents" else None
            run_question(question.strip(), use_hybrid, sources)

    result = st.session_state.get("last_result")
    if result:
        answer_text = html.escape(result["answer"])
        fallback_class = " fallback" if result["fallback_triggered"] else ""
        st.markdown(f'<div class="hero-answer{fallback_class}">{answer_text}</div>', unsafe_allow_html=True)

        source_by_chunk_id = {chunk["chunk_id"]: chunk["source_name"] for chunk in result["chunks"]}
        sources_seen = list(dict.fromkeys(source_by_chunk_id.values()))
        if sources_seen:
            st.markdown('<div class="section-label">Sources</div>', unsafe_allow_html=True)
            st.markdown(render_sources(sources_seen), unsafe_allow_html=True)

        col_confidence, col_citations = st.columns(2)

        with col_confidence:
            st.markdown('<div class="section-label">Confidence breakdown</div>', unsafe_allow_html=True)
            c = result["confidence"]
            meters = (
                render_meter("Retrieval", c["retrieval"])
                + render_meter("Citation coverage", c["citation"])
                + render_meter("Completeness", c["completeness"])
                + render_meter("Composite (gates fallback)", c["composite"], status_aware=True)
            )
            st.markdown(meters, unsafe_allow_html=True)

        with col_citations:
            st.markdown('<div class="section-label">Citations</div>', unsafe_allow_html=True)
            if result["citations"]:
                rows = "".join(
                    '<div style="margin-bottom:10px;">'
                    f'{render_badge(c["supported"])} '
                    f'<span style="font-size:0.85rem;">[{c["citation_number"]}] {html.escape(c["claim"])}</span> '
                    f'<span class="citation-source">— {html.escape(source_by_chunk_id.get(c["chunk_id"], "unknown"))}</span>'
                    "</div>"
                    for c in result["citations"]
                )
                st.markdown(rows, unsafe_allow_html=True)
            else:
                st.markdown(
                    '<span style="color:var(--text-muted); font-size:0.85rem;">No citations to verify.</span>',
                    unsafe_allow_html=True,
                )

        st.markdown('<div class="section-label">Retrieved chunks</div>', unsafe_allow_html=True)
        for rank, chunk in enumerate(result["chunks"], start=1):
            st.markdown(
                render_chunk_card(
                    chunk["source_name"], chunk["section_heading"], chunk["score"], chunk["text"], rank
                ),
                unsafe_allow_html=True,
            )

with tab_documents:
    st.markdown('<div class="section-label">Indexed documents</div>', unsafe_allow_html=True)
    try:
        docs = backend.documents()
        if docs:
            st.dataframe(docs, width="stretch", hide_index=True)
        else:
            st.info("No documents indexed yet. Add some below to get started.")
    except BackendError as e:
        st.error(f"Couldn't load documents: {e}")

    if not backend.uploads_enabled:
        st.caption("Uploads are turned off in the public demo. Run the project locally to index your own documents.")
    else:
        with st.expander("Add documents", expanded=True):
            st.caption(
                "1. Choose one or more files.  2. Click **Upload & index**.  3. They'll show up in "
                "the table above once indexing finishes.\n\n"
                "Files are sent to the API, saved into its corpus folder, and the whole corpus is "
                "then re-indexed — exact duplicates of chunks already indexed are skipped "
                "automatically, so re-uploading something is harmless."
            )
            uploaded_files = st.file_uploader(
                "md, txt, html, docx, or pdf",
                type=["md", "txt", "html", "docx", "pdf"],
                accept_multiple_files=True,
            )
            if uploaded_files and st.button("Upload & index"):
                with st.spinner("Uploading, chunking, embedding, and indexing..."):
                    try:
                        stats = backend.upload([(f.name, f.getvalue()) for f in uploaded_files])
                        st.success(
                            f"Uploaded {len(stats['uploaded'])} file(s), indexed {stats['indexed']} chunks "
                            f"({stats['deduped']} deduped as exact matches)."
                        )
                    except BackendError as e:
                        st.error(f"Ingestion failed: {e}")

with tab_eval:
    st.markdown('<div class="section-label">Chunking strategy comparison</div>', unsafe_allow_html=True)
    if COMPARISON_PATH.exists():
        summaries = json.loads(COMPARISON_PATH.read_text())
        rows = []
        for s in summaries:
            overall = s["scores"]["overall"]
            rows.append(
                {
                    "strategy": s["strategy"],
                    "chunks": s["chunks_indexed"],
                    "deduped": s["chunks_deduped"],
                    "mean tokens/chunk": s["mean_chunk_tokens"],
                    "correctness": overall["correctness"],
                    "faithfulness": overall["faithfulness"],
                    "retrieval relevance": overall["retrieval_relevance"],
                    "citation accuracy": overall["citation_accuracy"],
                    "fallback rate": overall["fallback_rate"],
                }
            )
        st.dataframe(rows, width="stretch", hide_index=True)

        chips = "".join(
            f'<span style="margin-right:18px;">{render_strategy_chip(r["strategy"])}</span>' for r in rows
        )
        st.markdown(f'<div style="margin-top:8px;">{chips}</div>', unsafe_allow_html=True)
    else:
        if IS_DEMO:
            st.info(f"No evaluation results published with this demo yet. See the [GitHub repo]({GITHUB_URL}) for the evaluation suite.")
        else:
            st.info("No comparison results yet. Run `python scripts/run_eval.py` first.")
